version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: Build the frontend
          command: |
            cd frontend
            yarn
            yarn build

  deploy:
    docker:
      - image: flyio/flyctl:latest
    steps:
      - checkout
      - run: flyctl auth login --token "$FLY_API_KEY"
      # Use the "flyctl deploy" command instead of the "flyctl deploy" step
      - run: flyctl deploy --image my-nextjs-app --remote-only

workflows:
  capstone:
    jobs:
      - build
      - deploy
