version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: Build the frontend
          command: |
            cd frontend
            yarn
            yarn build

workflows:
  capstone:
    jobs:
      - build
