version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run:
          name: Build the frontend
          command: |
            cd frontend
            yarn
            yarn build
            curl -L https://fly.io/install.sh | sh

      - run:
          name: deploy to fly.io
          command: |
            apt-get -y update
            apt-get -y install curl
            cd frontend
            flyctl auth login -t "$FLY_API_KEY"
            echo 'login succesful'
            flyctl deploy --remote-only

workflows:
  capstone:
    jobs:
      - build
