version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run:
          name: Build the frontend
          command: |
            cd frontend
            yarn
            yarn build

  deploy:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: deploy to fly.io
          command: |
            apt-get -y update
            apt-get -y install curl
            cd frontend
            curl -L https://fly.io/install.sh | sh

            /root/.fly/bin/flyctl auth login --token "$FLY_API_KEY"
            /root/.fly/bin/flyctl deploy --remote-only

workflows:
  capstone:
    jobs:
      - build
      - deploy:
          requires:
            - build
