version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    environment:
      FLY_API_KEY: '${FLY_API_KEY}'
    steps:
      - checkout
      - run:
          name: Build the frontend
          command: |
            cd frontend
            yarn
            yarn build

  dockerizeanddeploy:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      FLY_API_KEY: $FLY_API_KEY
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI

      # build the application image and check dockerlint by hadolint
      - run: |
          cd frontend
          # docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile
          docker build -t my-next-app .
          echo $FLY_API_KEY
          curl -L https://fly.io/install.sh | sh
          echo 'Hi'
          /home/circleci/.fly/bin/flyctl auth login
          /home/circleci/.fly/bin/flyctl deploy --image my-nextjs-app --remote-only

workflows:
  Final Project:
    jobs:
      - build
      - dockerizeanddeploy:
          requires:
            - build
