version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    environment:
      FLY_API_KEY: '${FLY_API_KEY}'
    steps:
      - checkout
      - run:
          name: Build the frontend
          command: |
            cd frontend
            yarn
            yarn build

  dockerizeanddeploy:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      FLY_API_KEY: $FLY_API_KEY
    steps:
      - checkout
      # Install Docker
      - run: # print the name of the branch we're on
          name: 'What branch am I on?'
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: 'What was my custom environment variable?'
          command: echo ${FLY_API_KEY}
      - run: sudo apt-get update
      - run: curl -L https://fly.io/install.sh | sh
      # Authenticate with fly.io
      - run: /home/circleci/.fly/bin/flyctl auth login -t ${FLY_API_KEY}
      # Build the Docker image and deploy to fly.io
      - run: |
          cd frontend
          docker build -t my-nextjs-app .
          /home/circleci/.fly/bin/flyctl deploy --image my-nextjs-app --remote-only

workflows:
  Final Project:
    jobs:
      - build
      - dockerizeanddeploy:
          requires:
            - build
