version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    environment:
      FLY_API_KEY: '${FLY_API_KEY}'
    steps:
      - checkout
      - run:
          name: Build the frontend
          command: |
            cd frontend
            yarn
            yarn build

  dockerizeanddeploy:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      FLY_API_KEY: $FLY_API_KEY
    steps:
      - checkout
      # Install Docker
      - run: sudo apt-get update && sudo apt-get install -y docker.io
      - run: curl -L https://fly.io/install.sh | sh
      # Authenticate with fly.io
      - run: flyctl auth login --token "$FLY_API_KEY"
      # Build the Docker image and deploy to fly.io
      - run: |
          cd frontend
          # docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile
          docker build -t my-nextjs-app .
          /home/circleci/.fly/bin/flyctl deploy --image my-nextjs-app --remote-only

workflows:
  Final Project:
    jobs:
      - build
      - dockerizeanddeploy:
          requires:
            - build
