version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    environment:
      FLY_API_KEY: '${FLY_API_KEY}'
    steps:
      - checkout
      - run:
          name: Build the frontend
          command: |
            cd frontend
            yarn
            yarn build

      - run:
          name: deploy to fly.io
          command: |
            curl -L https://fly.io/install.sh | sh
            cd frontend
            echo 'login succesful'
            /home/circleci/.fly/bin/flyctl deploy

workflows:
  capstone:
    jobs:
      - build
